AccessLog:
  comment: "Le chemin du fichier de logs d'acc\xE8s (AccessLog)."
  value: /chemin/vers/le/fichier/access.log
AllowOverride:
  comment: "Le param\xE8tre AllowOverride (All/None).Il est conseille de le mettre\
    \ a None si vous ne compter pas utiliser un fichier .htaccess"
  value: All
AtomicOperations:
  comment: "Activer les op\xE9rations atomiques (true/false)."
  value: true
DocumentRoot:
  comment: "Le chemin du r\xE9pertoire racine du site (DocumentRoot)."
  value: /chemin/vers/le/repertoire
EnableCaching:
  comment: Activer la mise en cache (true/false).
  value: true
EnableCompression:
  comment: Activer la compression (true/false).
  value: true
IncreaseChildProcesses:
  comment: Augmenter le nombre de processus/threads enfants (true/false).
  value: true
MPM:
  comment: Choisir un Module Multi-Processus (MPM).
  value: event
MaxRequestWorkers:
  comment: "Le nombre maximal de travailleurs simultan\xE9s."
  value: '150'
ProcessCreation:
  comment: Process Creation (posix/simple).
  value: posix
Sendfile:
  comment: Activer Sendfile (true/false). Il est conseiller de le desactiver
  value: true
ServerName:
  comment: Le nom de domaine du site.
  value: google.com
mmap:
  comment: Activer mmap (true/false). Il est conseille de le desactiver
  value: true
