
Worker:
    worker_processes: auto
    worker_rlimit_nofile: 100000
Buffers:
    client_body_buffer_size: 16k
    client_header_buffer_size: 3k
    client_max_body_size: 20m
    large_client_header_buffers: 2 3k
Proxy:
    proxy_buffering: on
    proxy_buffer_size: 8k
    proxy_buffers: 12 4k
Timeout:
    client_body_timeout: 30s
    client_header_timeout: 10
    keepalive_timeout: 30
    send_timeout: 60 
    keepalive_requests: 100
Compression:
    gzip: on
    gzip_types:  application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy
TCP:
    sendfile: on
    tcp_nodelay: on
    tcp_nopush: on
events:
    worker_connections: 100000
ProxyCache:
    proxy_cache_path: /var/cache/nginx levels=1:2 keys_zone=my_cache:10m inactive=60m;
server: 
    proxy_cache: my_cache
    proxy_cache_valid: 200 60m
    listen_ipv6_80: "[::]:80"
    listen_ipv4_80: "80"
    listen_ipv6_443: "[::]:443 ssl http2"
    listen_ipv4_443: "443 ssl http2"
SSL:
    ssl_session_cache: shared:SSL:10m
    ssl_session_timeout: 24h
    ssl_buffer_size: 1400
    ssl_stapling: on
    ssl_stapling_verify: on
    resolver: 8.8.8.8 8.8.4.4 216.146.35.35 216.146.36.36 valid=60s
    resolver_timeout: 2s
http:
    server_tokens: "off"
    add_headers:
        - name: "X-Frame-Options"
          value: "SAMEORIGIN"
          always: true
        - name: "Strict-Transport-Security"
          value: "max-age=31536000"
        - name: "X-XSS-Protection"
          value: "1; mode=block"
        - name: "default-src"
          value: "'self' https: data: 'unsafe-inline' 'unsafe-eval' always"
        - name: "X-Content-Type-Options"
          value: "nosniff always"
          always: true
        - name: "proxy_hide_header"
          value: "X-Powered-By"
        - name: "more_clear_headers"
          value: "X-Powered-By"
        - name: "Referrer-Policy"
          value: "origin-when-cross-origin always"
          always: true
Security:
    ssl_protocols: TLSv1.2 TLSv1.3
    ssl_prefer_server_ciphers: on
